CREATE DATABASE apppyme;

-- public.rol definition

-- Drop table

-- DROP TABLE public.rol;

CREATE TABLE public.rol (
	descripcion varchar NOT NULL,
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT rol_pk PRIMARY KEY (id)
);

-- public.tokenotp definition

-- Drop table

-- DROP TABLE public.tokenotp;

CREATE TABLE public.tokenotp (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"token" varchar NOT NULL,
	fechadecreacion timestamp NOT NULL,
	fechadevencimiento timestamp NOT NULL,
	esvalido bool NOT NULL,
	estaverificado bool NOT NULL,
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY
);

-- public.img definition

-- Drop table

-- DROP TABLE public.img;

CREATE TABLE public.img (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	"base64" varchar NOT NULL,
	fecha timestamp NOT NULL,
	CONSTRAINT img_pk PRIMARY KEY (id)
);

-- public.plataforma definition

-- Drop table

-- DROP TABLE public.plataforma;

CREATE TABLE public.plataforma (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	nombre varchar NOT NULL,
	img_id int4 NOT NULL,
	CONSTRAINT plataforma_pk PRIMARY KEY (id)
);

-- public.desarrolladora definition

-- Drop table

-- DROP TABLE public.desarrolladora;

CREATE TABLE public.desarrolladora (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	nombre varchar NOT NULL,
	img_id int4 NOT NULL,
	CONSTRAINT desarrolladora_pk PRIMARY KEY (id)
);

-- public.categoria definition

-- Drop table

-- DROP TABLE public.categoria;

CREATE TABLE public.categoria (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	nombre varchar NOT NULL,
	CONSTRAINT categoria_pk PRIMARY KEY (id)
);

-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	email varchar NOT NULL,
	"password" varchar NOT NULL,
	rol_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cuentaactiva bool NOT NULL,
	img_id int4 NULL,
	nombre varchar NOT NULL,
	departamento varchar NOT NULL,
	municipio varchar NOT NULL,
	fechanacimiento timestamp NOT NULL,
	fechaemidoc timestamp NOT NULL,
	fechavendoc timestamp NOT NULL,
	genero varchar NOT NULL,
	numdoc varchar NOT NULL,
	tipodoc varchar NOT NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id)
);


-- public.booking definition

-- Drop table

-- DROP TABLE public.booking;

CREATE TABLE public.booking (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	listp varchar NOT NULL,
	fecha timestamp NOT NULL,
	vigente bool NOT NULL,
	pagada bool NOT NULL,
	cancelada bool NOT NULL,
	CONSTRAINT booking_pk PRIMARY KEY (id)
);


-- public.compra definition

-- Drop table

-- DROP TABLE public.compra;

CREATE TABLE public.compra (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	agente_id int4 NOT NULL,
	user_id int4 NULL,
	fecha timestamp NOT NULL,
	CONSTRAINT compra_pk PRIMARY KEY (id)
);


-- public.cabecerafac definition

-- Drop table

-- DROP TABLE public.cabecerafac;

CREATE TABLE public.cabecerafac (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	img_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tipodoc varchar NOT NULL,
	numdoc varchar NOT NULL,
	fecha timestamp NOT NULL,
	metpag varchar NOT NULL,
	nombre varchar NOT NULL,
	total float8 NOT NULL,
	compra_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT cabecerafac_pk PRIMARY KEY (id)
);


-- public.detallefac definition

-- Drop table

-- DROP TABLE public.detallefac;

CREATE TABLE public.detallefac (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	cabecerafac_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	producto_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cantidad int4 NOT NULL,
	preciounitario float8 NOT NULL,
	subtotal float8 NOT NULL,
	CONSTRAINT detallefac_pk PRIMARY KEY (id)
);

-- public.producto definition

-- Drop table

-- DROP TABLE public.producto;

CREATE TABLE public.producto (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	nombre varchar NOT NULL,
	categoria_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	precio float8 NOT NULL,
	fechalanzamiento timestamp NOT NULL,
	desarrolladora_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	img_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cantidaddisponible int4 NOT NULL,
	plataforma_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar NOT NULL,
	fechapublicacion timestamp NOT NULL,
	CONSTRAINT videojuego_pk PRIMARY KEY (id)
);


-- public.tokenotp foreign keys

ALTER TABLE public.tokenotp ADD CONSTRAINT tokenotp_fk FOREIGN KEY (user_id) REFERENCES public."user"(id);

-- public."user" foreign keys

ALTER TABLE public."user" ADD CONSTRAINT user_fk FOREIGN KEY (img_id) REFERENCES public.img(id);
ALTER TABLE public."user" ADD CONSTRAINT usuario_fk FOREIGN KEY (rol_id) REFERENCES public.rol(id);

-- public.booking foreign keys

ALTER TABLE public.booking ADD CONSTRAINT booking_fk FOREIGN KEY (user_id) REFERENCES public."user"(id);


-- public.compra foreign keys

ALTER TABLE public.compra ADD CONSTRAINT compra_fk FOREIGN KEY (agente_id) REFERENCES public."user"(id);
ALTER TABLE public.compra ADD CONSTRAINT compra_fk_1 FOREIGN KEY (user_id) REFERENCES public."user"(id);


-- public.cabecerafac foreign keys

ALTER TABLE public.cabecerafac ADD CONSTRAINT cabecerafac_fk FOREIGN KEY (user_id) REFERENCES public."user"(id);
ALTER TABLE public.cabecerafac ADD CONSTRAINT cabecerafac_fk_1 FOREIGN KEY (compra_id) REFERENCES public.compra(id);
ALTER TABLE public.cabecerafac ADD CONSTRAINT cabecerafac_fk_2 FOREIGN KEY (img_id) REFERENCES public.img(id);

-- public.detallefac foreign keys

ALTER TABLE public.detallefac ADD CONSTRAINT detallefac_fk FOREIGN KEY (cabecerafac_id) REFERENCES public.cabecerafac(id);
ALTER TABLE public.detallefac ADD CONSTRAINT detallefac_fk_1 FOREIGN KEY (producto_id) REFERENCES public.producto(id);


-- public.producto foreign keys

ALTER TABLE public.producto ADD CONSTRAINT producto_fk FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);
ALTER TABLE public.producto ADD CONSTRAINT videojuego_fk_1 FOREIGN KEY (desarrolladora_id) REFERENCES public.desarrolladora(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.producto ADD CONSTRAINT videojuego_fk_2 FOREIGN KEY (img_id) REFERENCES public.img(id);
ALTER TABLE public.producto ADD CONSTRAINT videojuego_fk_3 FOREIGN KEY (plataforma_id) REFERENCES public.plataforma(id);


